//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaVeIT_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int newId { get; set; }
        public string newName { get; set; }
        public byte[] newImg { get; set; }
        public Nullable<System.DateTime> newDate { get; set; }
        public string newContent { get; set; }
    }
}
