
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SaVeIT_Final.Models
{
    //remote validation from SeniorProject model I have seperated it because model classes autogenerated after every update to a database
    public partial class ProjectValidation
    {
        [Required]
        public Nullable<short> Year { get; set; }
        [Required]
        [Remote("IsSectionAvailable", "SeniorProjectt", AdditionalFields = "Year",
 ErrorMessage = "This section already exists in this year")]
        public string Section { get; set; }

    }
}