//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaVeIT_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stu_Projects
    {
        public int PId { get; set; }
        public Nullable<int> StuId { get; set; }
        public int Id { get; set; }
        public string studentUserId { get; set; }
    
        public virtual SeniorProject SeniorProject { get; set; }
        public virtual Student Student { get; set; }
    }
}
