//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaVeIT_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupAOI
    {
        public int Id { get; set; }
        public int AOIId { get; set; }
        public string supervisorId { get; set; }
        public string supervisorUserId { get; set; }
    
        public virtual AreaOFInterest AreaOFInterest { get; set; }
        public virtual User User { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
